### ISSUE TITLE
Source Maps sendo deployados junto dos artefatos de build

### ISSUE THREAD

**Issue by mathcale** [Alvarenga-Dev/Github-Compare#1]
## O Problema

Quando você executa o comando `yarn build`, por padrão o `react-scripts` irá gerar os [source maps](https://www.html5rocks.com/en/tutorials/developertools/sourcemaps/) do seu projeto, que são muito úteis em tempo de desenvolvimento pois você consegue debuggar arquivos minificados, mas é um comportamento que você **deve evitar** em produção, uma vez que os browsers modernos irão interpretar os source maps e mostrar os arquivos fontes mesmo que seu servidor esteja apontado para a pasta `/build`, por exemplo.

Isso se torna um problemão quando seu projeto não é open source e uma grande parte do seu código-fonte e dependências se tornam públicos.

![Captura de Tela 2020-05-22 às 12 32 01](https://user-images.githubusercontent.com/6223070/82684042-5eb88f80-9c28-11ea-9e4b-feab29d2f350.png)

## A Resolução

Molezinha, é só adicionar a seguinte variável de ambiente no script de build no `package.json`:

```
"build": "GENERATE_SOURCEMAP=false react-scripts build"
```

**Comment by Alvarenga-Dev** [comment]
Obrigado! Não sabia dessa, vou procurar me atentar a isso, não sou muito de utilizar React.js no meu dia a dia, mas como irei utilizar ele para construir meu portfólio, saber sobre isso vai me ajudar muito! Já vou fazer isso no meu outro projeto.

Valeu mesmo pela issue, é bom que estou treinando meu Git hahaha
